#!/usr/bin/env python3
"""Apply ch24 prose rewrites. Fails loudly on any non-unique match."""
import sys

PATH = '/home/hatch/workspace/dba-library/book/ch24-caching.html'
C = 'bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs'
def code(x): return '<code class="%s">%s</code>' % (C, x)

REPLACEMENTS = [
# 1 intro
("""This chapter covers how PostgreSQL and SQL Server approach caching internally, how you as a DBA can observe and influence those mechanisms, and how application-layer and query-result caching strategies complement what the database engine provides.""",
 """This chapter covers how SQL Server approaches caching internally, how you as a DBA can observe and influence those mechanisms, and how application-layer and query-result caching strategies complement what the database engine provides."""),

# 2 shared buffers
("""In PostgreSQL, this memory region is called <strong class="text-white">shared buffers</strong>. Every backend process that executes a query shares access to this pool. When PostgreSQL reads a page from disk, it writes it into shared buffers, and subsequent requests for the same page find it there. The default size for shared buffers is 128 MB, a conservative value that almost every production deployment should raise significantly. A common starting point for a dedicated database server is 25% of total system RAM, though workload characteristics ultimately determine the right value.""",
 """In SQL Server, this memory region is the <strong class="text-white">buffer pool</strong>. Every query that reads a page goes through it: when SQL Server reads a page from disk, it loads it into the buffer pool, and subsequent requests for the same page are served from memory. SQL Server manages this memory dynamically — by default it will take nearly all available RAM — so the critical DBA decision is the """ + code('max server memory') + """ setting: cap it explicitly and leave headroom for the OS, the thread stacks, and anything else on the box. On a dedicated database server, reserving 4-8 GB (or roughly ten percent) for the OS and giving the rest to SQL Server is the standard starting point."""),

# 3 LRU both engines
("""Both engines use variations of the <strong class="text-white">LRU (Least Recently Used)</strong> algorithm to decide which pages to evict when the buffer pool fills up. PostgreSQL uses a clock-sweep algorithm, a practical approximation of LRU that avoids the overhead of maintaining a strict ordered list. SQL Server uses a more sophisticated version that also considers page reference counts and system memory pressure signals. In both systems, hot pages — those accessed frequently — tend to stay in memory, while cold pages get pushed out as new data enters.""",
 """SQL Server uses an LRU-K style algorithm to decide which pages to evict when the buffer pool fills up — weighing how recently and how frequently each page was touched, plus system memory pressure signals. Hot pages — those accessed frequently — tend to stay in memory, while cold pages get pushed out as new data enters. When Windows signals memory pressure, SQL Server trims the buffer pool cooperatively rather than fighting the OS for pages."""),

# 4 measure both
("""Before you can optimize caching, you need to measure it. Both PostgreSQL and SQL Server expose cache hit rate information through system views, and this metric tells you how often your workload is being served from memory versus disk.""",
 """Before you can optimize caching, you need to measure it. SQL Server exposes the buffer cache hit ratio through both the %s performance counter and %s, and this metric tells you how often your workload is being served from memory versus disk.""" % (code('Buffer cache hit ratio'), code('sys.dm_os_performance_counters'))),

# 5 pg_statio
("""In PostgreSQL, the %s view tracks buffer hits and disk reads per table. A buffer hit means the requested block was found in shared buffers. A block read means the engine had to go to disk (or the OS file system cache, discussed shortly).""" % code('pg_statio_user_tables'),
 """The %s DMV shows how many buffer pool pages each database currently holds, which tells you where your memory is actually going. A database whose working set doesn't fit will show a depressed cache hit ratio and elevated %s / %s counters — the signature of a buffer pool under pressure.""" % (code('sys.dm_os_buffer_descriptors'), code('page reads/sec'), code('page writes/sec'))),

# 6 low hit ratio PG
("""You can also look at which specific tables are generating the most disk reads, which helps prioritize tuning efforts. In PostgreSQL, tables with a persistently low hit ratio may benefit from either a larger shared_buffers value or investigation into whether large sequential scans are polluting the buffer pool with data that is only needed once.""",
 """You can also look at which databases and objects are generating the most physical reads, which helps prioritize tuning efforts. A persistently low buffer cache hit ratio usually means one of two things: the buffer pool is undersized for the working set (raise %s), or large scans are polluting it with data that is only needed once — in which case the fix is routing that workload to a readable secondary or a columnstore, not more memory.""" % code('max server memory')),

# 7 OS page cache
("""There is a layer of caching that many DBAs overlook: the operating system's own page cache. When PostgreSQL reads a page from disk, the operating system reads it through the file system into its own kernel page cache before PostgreSQL copies it into shared buffers. This means a page may actually be cached in two places: the OS page cache and PostgreSQL's shared buffers.""",
 """There is a layer of caching that many DBAs overlook: the operating system's own page cache. On Linux, when SQL Server reads a page from disk, it passes through the kernel page cache — so a page can effectively live in two places. On Windows, SQL Server opens database files with %s, bypassing the OS cache for database I/O; the buffer pool is the cache, full stop. Either way, the practical rule is the same: size the OS headroom first, then give SQL Server the rest via %s.""" % (code('FILE_FLAG_NO_BUFFERING'), code('max server memory'))),

# 8 effective_cache_size
("""This double-buffering is one reason why PostgreSQL's %s parameter exists. This parameter does not allocate any memory — it is purely a hint to the query planner indicating how much memory is available for caching across both shared buffers and the OS page cache combined. Setting it accurately helps the planner make better decisions about whether index scans (which benefit from cached pages) or sequential scans are more appropriate for a given query.""" % code('effective_cache_size'),
 """SQL Server's query optimizer needs no such hint — its cost model accounts for cached versus physical I/O internally, driven by statistics and the actual buffer pool state. There is no planner knob to tune here; the lever is the buffer pool size itself and keeping statistics current so the optimizer's cost estimates reflect reality."""),

# 9 direct I/O comparison
("""PostgreSQL does not use direct I/O by default — it goes through the OS page cache. This is deliberate; PostgreSQL benefits from the OS cache as a second tier. SQL Server on Windows can bypass the OS cache for some operations using FILE_FLAG_NO_BUFFERING, but the default behavior also goes through the Windows cache manager. On Linux, SQL Server behaves similarly to PostgreSQL in relying on the OS page cache.""" % (),
 """Because SQL Server bypasses the OS cache for database files on Windows, the buffer pool is genuinely the single tier of database caching — which is exactly why %s is the most consequential memory setting on the instance. Backup and bulk-load paths may still use the OS cache, but ordinary query I/O lives and dies by the buffer pool.""" % code('max server memory')),

# 10 64GB PG example
("""The practical implication is that tuning a database server means thinking about total memory holistically. On a 64 GB PostgreSQL server, setting shared_buffers to 16 GB and letting the OS use another 20–30 GB as a page cache is a reasonable configuration. The OS cache acts as an overflow layer — data that does not fit in shared buffers but is still needed frequently often gets served from the OS cache rather than actual disk, which is still significantly faster than a true cold disk read.""",
 """The practical implication is that tuning a database server means thinking about total memory holistically. On a 64 GB dedicated SQL Server box, setting %s to around 56 GB and leaving the rest for the OS is the standard starting point. There is no second-tier overflow cache for database pages on Windows — data that doesn't fit in the buffer pool goes to disk, period — so getting this number right matters more than any other memory decision you'll make.""" % code('max server memory')),

# 11 plan cache both
("""Parsing, analyzing, and planning a query takes CPU time. For a simple lookup query that executes thousands of times per second, re-planning the query on every execution is wasteful. Both PostgreSQL and SQL Server maintain a plan cache — an in-memory store of compiled query plans — that allows previously seen queries to skip the planning phase entirely.""",
 """Parsing, optimizing, and compiling a query takes CPU time. For a simple lookup query that executes thousands of times per second, re-compiling on every execution is wasteful. SQL Server maintains a plan cache — an in-memory store of compiled query plans — that allows previously seen queries to skip the optimization phase entirely, keyed by the query text hash."""),

# 12 PG prepared statements
("""PostgreSQL handles plan caching differently from SQL Server. In PostgreSQL, query plan caching happens primarily through <strong class="text-white">prepared statements</strong>. When a client prepares a statement using %s or a protocol-level prepare (as most connection poolers and ORMs do), PostgreSQL initially uses a generic plan after enough executions convince it that the generic plan is efficient. For the first five executions of a prepared statement, PostgreSQL creates a custom plan for each execution using the actual parameter values. After five executions, it evaluates whether a generic cached plan would be cheaper on average.""" % code('PREPARE'),
 """SQL Server caches plans for ad-hoc batches, %s calls, and stored procedures alike. Ad-hoc SQL benefits from <strong class="text-white">simple parameterization</strong> — the engine automatically parameterizes trivial queries so that %s and %s share one cached plan. For complex queries, parameterization doesn't happen automatically; that's what %s is for. If your workload is dominated by non-parameterized ad-hoc SQL, the plan cache fills with single-use plans — watch the %s counter, and consider %s at the database level before reaching for trace flags.""" % (code('sp_executesql'), code('SELECT * FROM Orders WHERE OrderId = 1'), code('SELECT * FROM Orders WHERE OrderId = 2'), code('sp_executesql'), code('Cache Hit Ratio'), code('forced parameterization'))),

# 13 plan_cache_mode
("""This behavior — called <strong class="text-white">plan stabilization</strong> — exists because the optimal plan for %s might differ from %s depending on data distribution. A generic plan must work reasonably well for all parameter values. The %s parameter (introduced in PostgreSQL 12) allows DBAs to force either always using custom plans (%s) or always using generic cached plans (%s), which is sometimes useful when dealing with parameters that have highly skewed distributions.""" % (code('WHERE customer_id = 1'), code('WHERE customer_id = 99999'), code('plan_cache_mode'), code('force_custom_plan'), code('force_generic_plan')),
 """This matters because the optimal plan for %s can differ wildly from %s depending on data distribution — the classic setup for <strong class="text-white">parameter sniffing</strong>, covered next. When the plan cache is polluted with single-use ad-hoc plans, the blunt instrument is %s, but that evicts every plan on the instance and causes a compile storm; prefer targeted fixes like forced parameterization or plan guides.""" % (code('WHERE customer_id = 1'), code('WHERE customer_id = 99999'), code('DBCC FREEPROCCACHE'))),

# 14 parameter sniffing + pg_stat_statements
("""SQL Server's equivalent challenge is <strong class="text-white">parameter sniffing</strong>. When SQL Server first compiles a plan for a stored procedure, it uses the actual parameter values at that moment to estimate cardinality, and the resulting plan is cached. If those initial values were unusual — either very selective or very broad — the cached plan may perform poorly for typical parameter values. This is one of the most common performance problems in SQL Server, and solutions range from %s on the query, to %s hints, to breaking procedures into smaller pieces. From PostgreSQL 16 onward, <strong class="text-white">query identifier</strong> tracking through %s makes it easier to identify plan instability patterns without needing to instrument the application layer.""" % (code('OPTION (RECOMPILE)'), code('OPTIMIZE FOR'), code('pg_stat_statements')),
 """SQL Server's signature plan-cache problem is <strong class="text-white">parameter sniffing</strong>. When SQL Server first compiles a plan for a stored procedure, it uses the actual parameter values at that moment to estimate cardinality, and the resulting plan is cached. If those initial values were unusual — either very selective or very broad — the cached plan may perform poorly for typical parameter values. This is one of the most common performance problems in SQL Server, and solutions range from %s on the query, to %s hints, to breaking procedures into smaller pieces. For plan instability that comes and goes, Query Store is the diagnostic tool: it captures the plan history per query so you can see exactly when the plan flipped and force the good one back.""" % (code('OPTION (RECOMPILE)'), code('OPTIMIZE FOR'))),

# 15 materialized views
("""PostgreSQL's %s is notable because it allows the view to remain queryable during the refresh — locks are minimal, and readers see the previous version of the data until the new version is ready. The %s option requires a unique index on the materialized view. SQL Server's indexed views are automatically maintained as the underlying data changes, which is both convenient and a source of overhead on write-heavy tables. The DBA must weigh the write overhead against the query performance gain.""" % (code('REFRESH MATERIALIZED VIEW CONCURRENTLY'), code('CONCURRENTLY')),
 """SQL Server's <strong class="text-white">indexed views</strong> are automatically maintained as the underlying data changes, which is both convenient and a source of overhead on write-heavy tables — every write to the base tables also maintains the view's clustered index. The DBA must weigh the write overhead against the query performance gain. Indexed views come with strict requirements (schema binding, deterministic expressions, and in Standard Edition the %s hint to use them), so for refresh-on-schedule semantics many shops instead maintain snapshot tables via Agent jobs — a manual materialized view with full control over refresh timing and locking.""" % code('NOEXPAND')),

# 16 ring buffers
("""<strong class="text-white">Cache eviction under memory pressure</strong> occurs when the buffer pool fills and the eviction algorithm must push out pages. In PostgreSQL, if a large ETL job or reporting query performs sequential scans over many tables, it will load millions of pages into shared buffers, potentially evicting hot pages that the OLTP workload depends on. PostgreSQL partially mitigates this through a mechanism called <strong class="text-white">ring buffers</strong> for sequential scans: large sequential scans use a small, fixed ring of buffer slots rather than populating the full shared buffer pool. This is automatic for scans over tables larger than a certain threshold (roughly 256 KB by default, controlled by %s and internal heuristics). The result is that sequential scans of large tables do not destroy the buffer pool, though they can still contribute to pressure.""" % code('effective_io_concurrency'),
 """<strong class="text-white">Cache eviction under memory pressure</strong> occurs when the buffer pool fills and the eviction algorithm must push out pages. If a large ETL job or reporting query scans a multi-gigabyte table, it will load millions of pages into the buffer pool, potentially evicting hot pages that the OLTP workload depends on. SQL Server has no ring-buffer protection for this — a big scan genuinely washes through the pool. The mitigations are architectural: route analytics to a readable secondary, reach for a columnstore index so the scan touches far fewer pages, or schedule the heavy scan for off-peak hours. Never "fix" it with %s in production — that evicts everything, including the hot pages you were trying to protect.""" % code('DBCC DROPCLEANBUFFERS')),

# 17 read replica routing
("""<strong class="text-white">Cache pollution</strong> from analytics workloads is a real problem that many teams address by routing analytical queries to a read replica. Both PostgreSQL streaming replication and SQL Server Always On Availability Groups support read-intent replicas. Directing reporting workloads to the replica not only keeps the primary's buffer pool clean but also offloads CPU and I/O from the primary entirely.""",
 """<strong class="text-white">Cache pollution</strong> from analytics workloads is a real problem that many teams address by routing analytical queries to a readable secondary. With read-only routing on the AG listener, connections marked %s land on secondaries automatically. Directing reporting workloads there not only keeps the primary's buffer pool clean but also offloads CPU and I/O from the primary entirely.""" % code('ApplicationIntent=ReadOnly')),

# 18 PgBouncer prepared statements
("""<strong class="text-white">Connection poolers and plan cache invalidation</strong> create a subtle problem. Tools like PgBouncer (for PostgreSQL) in session-mode maintain prepared statements across connection reuse, which is efficient. In transaction-mode pooling — where a client gets a backend connection only for the duration of a transaction — prepared statements cannot persist across transactions, because the client might get a different backend each time. This forces applications to use protocol-level prepared statements carefully, or to fall back to non-prepared queries, giving up plan cache benefits. When configuring a connection pooler, the DBA must understand whether the application relies on server-side prepared statements and choose the pooling mode accordingly.""",
 """<strong class="text-white">Connection pooling and the plan cache</strong> interact more benignly in SQL Server than in systems where pooling is a separate tier. Plans are cached server-side by query hash, independent of which pooled connection executed them — %s resets session state between checkouts but never evicts plans. So a well-pooled application using %s gets both benefits at once: cheap connection checkout and a warm plan cache. The thing pooling does <em>not</em> fix is cache bloat from non-parameterized ad-hoc SQL; that's a query-text problem, solved with parameterization, not with pool tuning.""" % (code('sp_reset_connection'), code('sp_executesql'))),

# 19 takeaway buffer pool
("""**The buffer pool is the primary cache** in both PostgreSQL (shared buffers) and SQL Server (Buffer Pool). Sizing it appropriately for the working data set is the single most impactful caching configuration decision a DBA makes.""",
 """**The buffer pool is the primary cache** in SQL Server. Sizing it via max server memory — appropriately for the working data set, with real OS headroom — is the single most impactful caching configuration decision a DBA makes."""),

# 20 takeaway plan caching
("""**Plan caching reduces planning overhead**, but each engine has failure modes — parameter sniffing in SQL Server and plan instability with skewed parameters in PostgreSQL. Understanding how to diagnose and address these without blunt tools like cache-clearing is an important production skill.""",
 """**Plan caching reduces compilation overhead**, but its failure modes — parameter sniffing and single-use plan bloat — are among the most common SQL Server performance problems. Understanding how to diagnose them with Query Store and address them without blunt tools like DBCC FREEPROCCACHE is an important production skill."""),

# 21 takeaway materialized views
("""**Application-layer caching through materialized views, Redis, or similar systems** reduces database read pressure for stable data, but requires careful invalidation strategies. Materialized views — whether PostgreSQL's refreshable variant or SQL Server's auto-maintained indexed views — are a powerful database-native option that does not require external infrastructure.""",
 """**Application-layer caching through indexed views, snapshot tables, Redis, or similar systems** reduces database read pressure for stable data, but requires careful invalidation strategies. SQL Server's auto-maintained indexed views are a powerful database-native option that does not require external infrastructure — as long as you budget for their write overhead."""),
]

def main():
    text = open(PATH).read()
    for i, (old, new) in enumerate(REPLACEMENTS):
        count = text.count(old)
        if count != 1:
            print(f'FAIL replacement {i}: found {count} occurrences')
            print('OLD SNIPPET:', old[:150])
            sys.exit(1)
        text = text.replace(old, new, 1)
    open(PATH, 'w').write(text)
    print(f'ch24: all {len(REPLACEMENTS)} replacements applied')

main()
