#!/usr/bin/env python3
"""Apply ch03 prose rewrites. Fails loudly on any non-unique match."""
import sys

PATH = '/home/hatch/workspace/dba-library/book/ch03-architecture.html'
C = 'bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs'

REPLACEMENTS = [
# --- section heading ---
(">How Each Engine Receives and Processes a Query<",
 ">How the Engine Receives and Processes a Query<"),

# --- B1 intro ---
("""This chapter walks through the architecture of both PostgreSQL and SQL Server, covering how each engine receives queries, processes them, manages memory, writes data to disk, and handles concurrency. By the end, you will see both systems clearly enough to compare them and know exactly which internal component to investigate when something goes wrong in production.""",
 """This chapter walks through the architecture of SQL Server, covering how the engine receives queries, processes them, manages memory, writes data to disk, and handles concurrency. By the end, you will see the system clearly enough to know exactly which internal component to investigate when something goes wrong in production."""),

# --- B2 postmaster -> SQLOS connection architecture ---
("""In <strong class="text-white">PostgreSQL</strong>, the process begins with the <strong class="text-white">postmaster</strong>, the parent process that listens on the network port (typically 5432) and spawns a dedicated backend process for each incoming client connection. This is a process-per-connection model. Each backend is an independent operating system process, which means a crash in one backend cannot corrupt the memory of another. The backend receives the query string and passes it through four stages: parsing, rewriting, planning, and execution.""",
 """In <strong class="text-white">SQL Server</strong>, everything runs inside a single service process (<code class="BG">sqlservr.exe</code>), scheduled by a user-mode operating system layer called <strong class="text-white">SQLOS</strong>. When a client connects — typically over the TDS (Tabular Data Stream) protocol on port 1433 — SQLOS assigns the connection to a scheduler (one per logical CPU) and lends it a worker thread from the thread pool. This thread-pool model means a thousand idle connections cost far less than a thousand OS processes would, but it also means worker-thread exhaustion is a real failure mode: when all workers are busy, new requests queue behind the <code class="BG">THREADPOOL</code> wait, and the instance stops accepting work even though CPU looks idle.""".replace('class="BG"', 'class="%s"' % C)),

# --- B3 parser/rewriter/planner -> SQL Server pipeline depth ---
("""The <strong class="text-white">parser</strong> converts the SQL text into an internal tree structure called a parse tree. The <strong class="text-white">rewriter</strong> applies any rewrite rules — most commonly, it expands views by substituting their definition into the query. The <strong class="text-white">planner</strong> (also called the optimizer) takes the rewritten query tree and generates one or more candidate execution plans, assigns cost estimates to each using statistics from <code class="BG">pg_statistic</code>, and selects the cheapest one. Finally, the <strong class="text-white">executor</strong> runs the chosen plan and streams rows back to the client.""".replace('class="BG"', 'class="%s"' % C),
 """The query text then travels a pipeline with four stages. The <strong class="text-white">parser</strong> checks syntax and builds a parse tree. The <strong class="text-white">algebrizer</strong> (also called the binder) resolves every object name, column reference, and data type against the system catalog, producing a logical operator tree. The <strong class="text-white">query optimizer</strong> — a cost-based Cascades-framework optimizer — explores equivalent plan shapes (join orders, join algorithms, access methods), estimates each candidate's cost using statistics from <code class="BG">sys.stats</code> and cardinality estimation, and picks the cheapest. Finally, the <strong class="text-white">execution engine</strong> runs the chosen plan and streams rows back to the client.""".replace('class="BG"', 'class="%s"' % C)),

# --- B4: fix analyzer comparison, refocus on plan cache ---
("""then into the <strong class="text-white">algebrizer</strong> (the SQL Server equivalent of PostgreSQL's analyzer), which resolves object names and data types.""",
 """then into the <strong class="text-white">algebrizer</strong>, which resolves object names and data types."""),
("""A compiled plan is stored in the <strong class="text-white">plan cache</strong> (part of the Buffer Pool). On subsequent executions of the same parameterized query, the engine looks up the cached plan to avoid recompilation overhead.""",
 """A compiled plan is stored in the <strong class="text-white">plan cache</strong>. On subsequent executions of the same parameterized query, the engine reuses the cached plan instead of recompiling — which is why the very first execution of a query (compile time included) is often slower than every execution after it."""),

# --- B5 plan cache comparison -> SQL Server depth ---
("""A key practical difference emerges here: PostgreSQL historically compiled a new plan for each execution of an ad-hoc query (though prepared statements cache plans), while SQL Server aggressively caches execution plans. This makes plan cache management an important SQL Server DBA task that has no direct equivalent in PostgreSQL day-to-day operations.""",
 """A key practical characteristic of the engine: SQL Server caches execution plans aggressively, which makes plan cache management a core DBA responsibility. Ad-hoc workloads can bloat the cache with thousands of single-use plans — the <code class="BG">optimize for ad hoc workloads</code> setting stores only a plan stub on first execution and the full plan on second use. And cached plans have a dark side: <strong class="text-white">parameter sniffing</strong>, where a plan optimized for one parameter value performs terribly for another, is one of the most common sources of "the query was fast yesterday" incidents. Query Store, covered later in this book, is the flight recorder that lets you prove it.""".replace('class="BG"', 'class="%s"' % C)),

# --- B6 mermaid diagram ---
('Rewrite["Rewriter / Algebrizer"]', 'Rewrite["Algebrizer"]'),
('Planner["Planner / Optimizer"]', 'Planner["Query Optimizer"]'),
('Disk[("Disk / WAL")]', 'Disk[("Disk / T-Log")]'),

# --- B7 figure caption ---
("""*Figure: The query processing pipeline shared by PostgreSQL and SQL Server — a client request is parsed, rewritten or algebrized, planned, matched against a cached plan where possible, and executed against the buffer pool before results stream back to the client.*""",
 """*Figure: The query processing pipeline in SQL Server — a client request is parsed, algebrized, optimized, matched against a cached plan where possible, and executed against the buffer pool before results stream back to the client.*"""),

# --- B8 memory intro ---
("""<strong class="text-white">PostgreSQL</strong> divides memory into two broad categories: shared memory and local (per-backend) memory.""",
 """<strong class="text-white">SQL Server</strong> manages memory as a unified pool governed by SQLOS's memory manager, bounded above by the <code class="BG">max server memory</code> setting. Within that pool, memory is tracked by <strong class="text-white">memory clerks</strong> — accounting components per subsystem (Buffer Pool, plan cache, connection memory, CLR) that you can inspect through <code class="BG">sys.dm_os_memory_clerks</code> when you need to find who is consuming RAM.""".replace('class="BG"', 'class="%s"' % C)),

# --- B9 shared_buffers -> Buffer Pool ---
("""<strong class="text-white">Shared memory</strong> is allocated once at startup and shared across all backend processes. The most important component is the <strong class="text-white">shared buffer pool</strong>, controlled by the <code class="BG">shared_buffers</code> parameter (default: 128MB, but production systems typically set this to 25–40% of total RAM). The shared buffer pool holds copies of data pages (each page is 8KB by default) read from disk. When a backend needs a data page, it first checks the shared buffer pool. A hit means the page is served from RAM; a miss means PostgreSQL must read the page from the operating system page cache or disk and bring it into shared buffers.""".replace('class="BG"', 'class="%s"' % C),
 """The most important component is the <strong class="text-white">Buffer Pool</strong>, controlled by the <code class="BG">max server memory</code> configuration. The Buffer Pool holds copies of 8KB data and index pages read from disk, plus cached execution plans. When a query needs a page, the engine first checks the Buffer Pool: a hit serves the page from RAM, a miss triggers a physical read and the page is cached for next time. The health metric that matters here is <strong class="text-white">Page Life Expectancy (PLE)</strong> — how long a page survives in the pool before eviction. A PLE that collapses under load means your working set no longer fits in memory, and no amount of query tuning will fix a memory-bound workload.""".replace('class="BG"', 'class="%s"' % C)),

# --- B10 OS page cache nuance -> SQL Server I/O ---
("""This is where PostgreSQL's architecture introduces an important nuance: PostgreSQL relies heavily on the <strong class="text-white">OS page cache</strong> as a second level of caching. A page evicted from shared buffers may still be in the OS cache, making its retrieval faster than a true disk read. This double-buffering behavior is a design trade-off — it means PostgreSQL does not need to implement its own complex cache eviction logic for all cases, but it also means memory usage is harder to predict and control precisely compared to SQL Server.""",
 """SQL Server manages its cache directly rather than leaning on the operating system's file cache for data files, which makes its memory behavior predictable and controllable: <code class="BG">max server memory</code> is a genuine ceiling, not a suggestion. The one critical OS-level interaction to configure is <strong class="text-white">Lock Pages in Memory</strong> — the Windows privilege that lets SQL Server lock its buffer pool in physical RAM so the OS never pages it to disk. Without it, Windows can page out buffer pool memory under pressure, producing the worst of both worlds: slow queries and an engine that believes it has memory it cannot actually touch.""".replace('class="BG"', 'class="%s"' % C)),

# --- B11 work_mem -> memory grants ---
("""Per-backend local memory includes structures like <code class="BG">work_mem</code> (used for sorts, hash joins, and hash aggregations — each sort or hash operation in a query plan can use up to <code class="BG">work_mem</code> bytes), <code class="BG">maintenance_work_mem</code> (used by VACUUM, CREATE INDEX, and CLUSTER), and <code class="BG">temp_buffers</code> (for temporary tables).""".replace('class="BG"', 'class="%s"' % C),
 """Beyond the Buffer Pool, queries need <strong class="text-white">workspace memory</strong> for sorts, hash joins, and hash aggregations. The optimizer requests a <strong class="text-white">memory grant</strong> before execution; if the grant is too small, the operation spills to tempdb and the query slows dramatically, and if too many queries wait for grants simultaneously you will see <code class="BG">RESOURCE_SEMAPHORE</code> waits — the signature of memory pressure at the query level. Memory grants that are wildly oversized are just as bad: they waste RAM and serialize concurrent queries. Sort and hash warnings in your monitoring are the smoke; grant sizing and tempdb throughput are the fire.""".replace('class="BG"', 'class="%s"' % C)),

# --- B12 Buffer Pool paragraph: remove PG comparisons ---
("""<strong class="text-white">SQL Server</strong> uses a unified memory pool called the <strong class="text-white">Buffer Pool</strong>, managed by a component called the <strong class="text-white">Buffer Manager</strong>. Unlike PostgreSQL's dual-layer approach, SQL Server manages its own cache directly, bypassing OS-level file caching for data files by using direct I/O (on Linux) or by competing with the OS cache carefully (on Windows). The Buffer Pool contains data pages (8KB, matching PostgreSQL's default), index pages, and execution context memory. SQL Server dynamically adjusts how much memory it allocates to the Buffer Pool based on system demand, bounded by the <code class="BG">max server memory</code> configuration.""".replace('class="BG"', 'class="%s"' % C),
 """The <strong class="text-white">Buffer Manager</strong> is the component that owns the Buffer Pool. It tracks every cached page's state, ages pages out under memory pressure using a clock algorithm, and coordinates with the Lazy Writer thread that keeps free buffers available. The Buffer Pool contains data pages (8KB), index pages, and execution context memory, and SQL Server dynamically balances these consumers against each other — plan cache bloat can starve data pages, which is one more reason ad-hoc plan cache hygiene matters."""),

# --- B13 PGDATA -> SQL Server files/filegroups ---
("""In <strong class="text-white">PostgreSQL</strong>, a database cluster (a single PostgreSQL installation) stores all its data under the <code class="BG">PGDATA</code> directory. Each database within a cluster has its own subdirectory under <code class="BG">PGDATA/base/</code>, identified by its OID (object identifier). Each table and index is stored as one or more files in that directory, also named by OID. By default, a relation file is capped at 1GB; once it reaches that size, PostgreSQL creates a numbered continuation file (e.g., <code class="BG">16384</code>, <code class="BG">16384.1</code>, <code class="BG">16384.2</code>).""".replace('class="BG"', 'class="%s"' % C),
 """In <strong class="text-white">SQL Server</strong>, every database is a set of operating-system files: one primary data file (<code class="BG">.mdf</code>), zero or more secondary data files (<code class="BG">.ndf</code>), and one or more transaction log files (<code class="BG">.ldf</code>). Files are organized into <strong class="text-white">filegroups</strong> — allocation containers that decide which physical files an object lives on. Every database has a <code class="BG">PRIMARY</code> filegroup holding system objects; best practice is to create dedicated filegroups for user data and indexes so growth, placement, and piecemeal restores can be managed independently. SQL Server fills files within a filegroup proportionally, striping new allocations across all files — which is why adding a second data file to a filegroup genuinely increases write throughput.""".replace('class="BG"', 'class="%s"' % C)),

# --- B14 PG page layout -> SQL Server page anatomy ---
("""The fundamental storage unit is the <strong class="text-white">page</strong> (8KB by default). Every heap file (table) and index file is a sequence of pages. Each page has a header, an array of item pointers (called the line pointer array), and rows stored from the bottom of the page upward. This layout means PostgreSQL can locate a specific row using a physical address called a <strong class="text-white">tuple ID (ctid)</strong>, which encodes the page number and the item pointer offset within that page.""",
 """The fundamental storage unit is the <strong class="text-white">page</strong>: 8KB, always. Every data file is a sequence of pages, each with a 96-byte header, the data rows themselves, and a row-offset array (slot array) at the end of the page that locates each row. This layout is why a heap row is addressed by its <strong class="text-white">RID</strong> — file ID, page ID, and slot number — and why page splits hurt: when an insert lands on a full page, the engine allocates a new page and moves half the rows, an operation that fragments the index and generates log records proportional to the data moved."""),

# --- B15 tablespaces -> filegroups ---
("""PostgreSQL also supports <strong class="text-white">tablespaces</strong>, which allow specific tables or indexes to be stored on different mount points or storage volumes — useful for placing hot indexes on NVMe storage and cold archive tables on slower, cheaper disks.""",
 """<strong class="text-white">Filegroups</strong> are also the mechanism for tiered storage: place hot indexes on NVMe-backed files and cold archive tables on slower, cheaper disks by creating the objects on different filegroups. Partitioned tables take this further — each partition can live on its own filegroup, so sliding-window partition maintenance can drop a month of data as a metadata operation instead of a logged delete of a billion rows."""),

# --- B16 WAL/pg_wal -> transaction log architecture ---
("""The <strong class="text-white">Write-Ahead Log (WAL)</strong> is stored separately under <code class="BG">PGDATA/pg_wal/</code>. Every change to data pages is first written as a WAL record before the data page itself is modified on disk. This is the mechanism that guarantees durability — if the system crashes after a WAL record is written but before the data page is flushed, PostgreSQL can replay the WAL record during recovery to reconstruct the change.""".replace('class="BG"', 'class="%s"' % C),
 """The <strong class="text-white">transaction log</strong> is stored separately in the database's <code class="BG">.ldf</code> file. Every change to data pages is first written as a log record before the data page itself is modified on disk. This is the mechanism that guarantees durability — if the system crashes after a log record is written but before the data page is flushed, SQL Server replays the log during recovery to reconstruct the change. Internally the log is divided into <strong class="text-white">virtual log files (VLFs)</strong>; too many tiny VLFs (from growing the log in small increments) slows recovery and replication, which is why log files should be sized deliberately and grown in large, infrequent chunks.""".replace('class="BG"', 'class="%s"' % C)),

# --- B17 equivalent-of-WAL paragraph ---
("""SQL Server's equivalent of PostgreSQL's WAL is the <strong class="text-white">transaction log</strong>. Every database has a transaction log that records all changes before they are applied to data pages. Log records are written sequentially, and SQL Server uses a <strong class="text-white">log sequence number (LSN)</strong> to track position in the log — directly analogous to PostgreSQL's LSN in the WAL.""",
 """The transaction log is the heart of SQL Server's durability story. Every database has a transaction log that records all changes before they are applied to data pages. Log records are written sequentially and chained by <strong class="text-white">log sequence numbers (LSNs)</strong>, which also order crash recovery, log shipping, and Availability Group redo. The log is truncated — its inactive portion marked reusable — only by log backups (in the FULL and BULK_LOGGED recovery models), which is why a database with no log backups will grow its log file until the disk fills and every write in the database stops."""),

# --- B18 heap-by-default vs clustered ---
("""One significant architectural difference worth understanding is how each system handles table storage by default. PostgreSQL stores all tables as <strong class="text-white">heap files</strong> — rows are stored in the order they are inserted (unless later reorganized by CLUSTER). SQL Server, by contrast, stores tables either as a <strong class="text-white">heap</strong> (when no clustered index exists) or as a <strong class="text-white">clustered index</strong>, where the table's row data is physically sorted by the clustered key and stored within the B-tree index structure. Most SQL Server tables in production are clustered indexes, making the choice of clustering key a design decision with major performance implications — a concern that simply does not arise in the same way in PostgreSQL.""",
 """SQL Server stores a table either as a <strong class="text-white">heap</strong> (when no clustered index exists) or as a <strong class="text-white">clustered index</strong>, where the table's row data is physically ordered by the clustered key and stored within the B-tree structure itself. Most production tables are clustered indexes, making the clustering-key choice a design decision with major performance implications. The ideal key is narrow, static, unique, and ever-increasing — an <code class="BG">IDENTITY</code> column or sequence — because it appends new rows at the logical end instead of splitting pages in the middle. A random GUID or frequently-updated wide key does the opposite: it fragments the table, and because every nonclustered index stores the clustering key as its row locator, a wide clustering key bloats every index on the table. Heaps have legitimate uses — staging tables and high-insert ETL landings — but updates that relocate rows leave forwarding pointers behind, so heaps need periodic rebuilds too.""".replace('class="BG"', 'class="%s"' % C)),

# --- B19 concurrency intro ---
("""A production database is never accessed by just one session at a time. Dozens, hundreds, or thousands of concurrent transactions may be reading and modifying data simultaneously. Concurrency control is the mechanism that keeps these transactions from interfering with each other in ways that produce incorrect results. Both PostgreSQL and SQL Server support the ACID properties (Atomicity, Consistency, Isolation, Durability), but they use fundamentally different approaches to achieve isolation.""",
 """A production database is never accessed by just one session at a time. Dozens, hundreds, or thousands of concurrent transactions may be reading and modifying data simultaneously. Concurrency control is the mechanism that keeps these transactions from interfering with each other in ways that produce incorrect results. SQL Server delivers the full ACID properties, and its concurrency story centers on <strong class="text-white">locking</strong> — with row-versioning options for workloads where blocking is unacceptable. Understanding the lock manager is non-optional: most "the database is slow" incidents are, at their root, concurrency incidents."""),

# --- B20 PG MVCC -> SQL Server locking ---
("""<strong class="text-white">PostgreSQL</strong> uses <strong class="text-white">Multi-Version Concurrency Control (MVCC)</strong> as its primary isolation mechanism. The core idea is that instead of locking a row when a transaction reads it, PostgreSQL maintains multiple versions of each row. When a row is updated, the old version is not overwritten; instead, a new version is written, and the old version is marked as expired. Each transaction sees a consistent snapshot of the data as it existed at the start of the transaction (for the default <code class="BG">READ COMMITTED</code> level) or at the start of the statement. This means <strong class="text-white">readers never block writers, and writers never block readers</strong> — a property that makes PostgreSQL excellent for mixed workloads.""".replace('class="BG"', 'class="%s"' % C),
 """<strong class="text-white">SQL Server</strong> uses <strong class="text-white">locking</strong> as its primary isolation mechanism. Locks form a hierarchy — database, table, page, row/key — and come in modes that compose: shared (S) locks for reads, exclusive (X) locks for writes, update (U) locks as a pre-write probe, and intent locks (IS, IX) at coarser granularities announcing what is happening below. Two transactions conflict when one holds a lock mode incompatible with what the other requests, and the loser waits — this is <strong class="text-white">blocking</strong>, the single most common cause of "slow database" complaints. When waiting forms a cycle, the engine picks a <strong class="text-white">deadlock</strong> victim and rolls it back with error 1205. Your job is not to eliminate locking — it is to keep transactions short, access objects in consistent order, and choose an isolation level whose guarantees match what the business actually needs."""),

# --- B21 xmin/xmax -> lock escalation ---
("""Each row version in PostgreSQL carries two hidden system columns: <code class="BG">xmin</code> (the transaction ID that created this version) and <code class="BG">xmax</code> (the transaction ID that deleted or superseded this version, or 0 if the row is still current). The visibility of a row to a given transaction is determined by comparing these values against the transaction's snapshot.""".replace('class="BG"', 'class="%s"' % C),
 """Lock granularity is the engine's cost-control mechanism: it starts with row or key locks and <strong class="text-white">escalates</strong> to page or table locks when a single statement acquires more than roughly 5,000 locks on one object. Escalation trades memory for blocking surface — it is the reason a big unbatched <code class="BG">UPDATE</code> can suddenly block the entire table instead of just the rows it touches. The fix is batching: process large modifications in controlled chunks (a few thousand rows per batch) so no single statement trips the escalation threshold.""".replace('class="BG"', 'class="%s"' % C)),

# --- B22 VACUUM necessity -> ghost records + version store ---
("""The downside of MVCC is that dead row versions accumulate over time, consuming disk space and degrading performance. This is why <strong class="text-white">VACUUM</strong> exists — it is not a cosmetic operation but an architectural necessity, responsible for reclaiming space occupied by dead tuples and updating the visibility map so that index-only scans remain efficient.""",
 """Cleanup is an architectural necessity, not an optional chore. Deleted rows leave behind <strong class="text-white">ghost records</strong> — the space is not reclaimed until the ghost cleanup task sweeps them, which is why index rebuilds and reorganizes remain routine maintenance rather than occasional emergencies. And when row versioning is enabled, superseded row versions accumulate in tempdb's <strong class="text-white">version store</strong> until no active transaction still needs them — so a single long-running transaction pins version-store growth and can bloat tempdb for the whole instance."""),

# --- B23 RCSI: fix comparison tail ---
("""However, SQL Server also offers an MVCC-style option called <strong class="text-white">Read Committed Snapshot Isolation (RCSI)</strong>.""",
 """SQL Server also offers an MVCC-style option called <strong class="text-white">Read Committed Snapshot Isolation (RCSI)</strong>."""),
("""Readers no longer acquire shared locks and are not blocked by writers, giving behavior similar to PostgreSQL's default. Enabling RCSI is one of the most impactful configuration changes you can make to a busy SQL Server OLTP database, and most modern SQL Server deployments should have it enabled.""",
 """Readers no longer acquire shared locks and are not blocked by writers — each statement sees a consistent snapshot of committed data as of the statement's start. Enabling RCSI is one of the most impactful configuration changes you can make to a busy SQL Server OLTP database, and most modern OLTP deployments should have it enabled — after sizing tempdb for the version-store load it creates."""),

# --- B24 SI: fix comparison tail ---
("""This is directly comparable to PostgreSQL's <code class="BG">REPEATABLE READ</code> or <code class="BG">SERIALIZABLE</code> isolation levels.""".replace('class="BG"', 'class="%s"' % C),
 """This is the right choice when a multi-statement transaction must see stable data throughout — end-of-day reporting batches, for example — at the cost of update conflicts (error 3960) when two snapshot transactions modify the same row."""),

# --- B25 background intro ---
("""A running database is not just the sum of its client connections. Both PostgreSQL and SQL Server maintain a fleet of background processes that handle critical maintenance work continuously. Understanding these processes helps you diagnose unexpected CPU or I/O spikes, configure maintenance windows appropriately, and understand what the database is doing when no client queries are running.""",
 """A running SQL Server instance is not just the sum of its client connections. The engine maintains dedicated background threads that handle checkpointing, lazy writing, ghost cleanup, and log flushing continuously. Understanding these threads helps you diagnose unexpected CPU or I/O spikes and understand what the database is doing when no client queries are running."""),

# --- B26 PG workers intro -> SQLOS threads intro ---
("""<strong class="text-white">PostgreSQL</strong> runs several background workers that are central to keeping the engine healthy:""",
 """<strong class="text-white">SQL Server's</strong> background work runs as threads inside the engine, scheduled by SQLOS alongside user worker threads. The ones you will encounter in production:"""),

# --- B27 autovacuum -> lazy writer / ghost cleanup / auto tuning ---
("""The <strong class="text-white">autovacuum launcher</strong> spawns autovacuum worker processes. These workers run VACUUM and ANALYZE on tables that have accumulated enough dead tuples or have had enough data changes to make the statistics stale. Autovacuum is often misunderstood as optional or as an overhead — in reality, neglecting it causes table bloat, index bloat, transaction ID wraparound (a serious failure condition), and increasingly inaccurate query plans. Autovacuum behavior is tunable per table, which is essential for large, high-churn tables.""",
 """The <strong class="text-white">Lazy Writer</strong> continuously scans the Buffer Pool for clean, aged-out pages to keep free buffers available. When it cannot keep up — the pool is full of dirty pages nobody is flushing — queries stall waiting for free buffers, and you will see it in the waits. The <strong class="text-white">Ghost Cleanup</strong> task reclaims space from deleted rows in the background. And <strong class="text-white">Automatic Tuning</strong> watches Query Store for plan regressions and can force the last known good plan on its own. None of these are optional overhead; they are the engine's self-maintenance, and their distress signals show up in your monitoring before users notice."""),

# --- B28 WAL writer/checkpointer/bgwriter -> log writer + checkpoint ---
("""The <strong class="text-white">WAL writer</strong> periodically flushes WAL buffers to disk, ensuring that WAL records do not remain in memory for too long regardless of commit activity. The <strong class="text-white">checkpointer</strong> is responsible for periodically flushing dirty data pages from shared buffers to disk, creating a known recovery point. Checkpoints are triggered either by time (<code class="BG">checkpoint_timeout</code>, default 5 minutes) or by WAL volume (<code class="BG">max_wal_size</code>). The <strong class="text-white">background writer</strong> assists the checkpointer by writing dirty pages to disk incrementally, reducing the I/O burst that would otherwise occur at each checkpoint.""".replace('class="BG"', 'class="%s"' % C),
 """The <strong class="text-white">Log Writer</strong> flushes the log buffer to the transaction log — on every commit, and whenever the buffer fills. Log flush latency is the floor under your transaction latency: slow log storage shows up directly as <code class="BG">WRITELOG</code> waits, the canonical signature of a log bottleneck. The <strong class="text-white">Checkpoint</strong> process periodically writes all dirty pages in the Buffer Pool to disk, bounding how much log must be replayed after a crash. SQL Server performs automatic checkpoints, indirect checkpoints (which bound recovery time per database and are the default since 2016), and manual checkpoints via the <code class="BG">CHECKPOINT</code> command.""".replace('class="BG"', 'class="%s"' % C)),

# --- B29 stats collector -> auto update stats ---
("""The <strong class="text-white">stats collector</strong> (in versions before PostgreSQL 15, a dedicated process; integrated in later versions) gathers activity statistics that populate the <code class="BG">pg_stat_*</code> family of views, which are the DBA's primary observability tool.""".replace('class="BG"', 'class="%s"' % C),
 """Statistics maintenance has no dedicated background thread — it is driven by the optimizer itself. <strong class="text-white">Auto-update statistics</strong> fires when a query's compilation detects that a table's modifications have crossed the refresh threshold, and with <code class="BG">AUTO_UPDATE_STATISTICS_ASYNC</code> enabled the current query proceeds on the old statistics while the refresh happens in the background. That single setting is the difference between one slow query and every query stalling on stats updates during a bulk load.""".replace('class="BG"', 'class="%s"' % C)),

# --- B30 checkpoint thread -> recovery interval depth ---
("""The <strong class="text-white">Checkpoint</strong> thread in SQL Server, like PostgreSQL's checkpointer, periodically writes all dirty pages in the Buffer Pool to disk. SQL Server performs automatic checkpoints, indirect checkpoints (which are more predictable in terms of recovery time), and manual checkpoints (<code class="BG">CHECKPOINT</code> command). The checkpoint frequency is influenced by the <code class="BG">recovery interval</code> setting, which controls the target recovery time after a crash.""".replace('class="BG"', 'class="%s"' % C),
 """The legacy <code class="BG">recovery interval</code> setting still bounds crash recovery at the instance level, but per-database <strong class="text-white">indirect checkpoints</strong> (via <code class="BG">TARGET_RECOVERY_TIME</code>) are the modern control: they make recovery time predictable per database instead of per instance. A manual <code class="BG">CHECKPOINT</code> before maintenance windows and bulk operations is still good hygiene — it empties the dirty-page backlog so the work that follows starts from a clean, known point.""".replace('class="BG"', 'class="%s"' % C)),

# --- B31 ghost cleanup: drop VACUUM analogy ---
("""SQL Server also has dedicated threads for <strong class="text-white">ghost cleanup</strong> (removing index entries for deleted rows that were marked as "ghost records" rather than immediately removed), which is roughly analogous to the portion of PostgreSQL's VACUUM that cleans index entries.""",
 """The <strong class="text-white">ghost cleanup</strong> thread removes index entries for deleted rows that were marked as ghost records rather than removed immediately. Ghost records are why a table can report more pages than its live rows justify — and why index rebuilds remain routine maintenance rather than occasional emergencies."""),

# --- B32 lead-in sentence ---
("""You can observe what PostgreSQL's background workers are doing at any moment:""",
 """You can observe what the engine's background threads are doing at any moment:"""),

# --- "How Architecture Shapes Production Decisions" intro: MVCC cleanup mention ---
("""Understanding where the engine is spending time — in the query planner, in memory pressure on the buffer pool, in MVCC cleanup, in lock contention — is only possible if you understand how those subsystems work and interact.""",
 """Understanding where the engine is spending time — in the query optimizer, in memory pressure on the buffer pool, in ghost cleanup and version-store growth, in lock contention — is only possible if you understand how those subsystems work and interact."""),

# --- B33 process-per-connection -> thread pool depth ---
("""The <strong class="text-white">process-per-connection</strong> model in PostgreSQL means that connection count directly translates to memory and process overhead. A PostgreSQL instance with 1,000 active connections is running 1,000 OS processes, each with its own memory allocation. This is why connection poolers like PgBouncer are effectively mandatory for high-concurrency PostgreSQL deployments. SQL Server's <strong class="text-white">thread-pool model</strong> handles high connection counts more gracefully at the OS level, but it introduces a different class of problems around thread exhaustion, MAXDOP settings, and thread scheduler contention (<code class="BG">CXPACKET</code> and related wait types).""".replace('class="BG"', 'class="%s"' % C),
 """The <strong class="text-white">thread-pool model</strong> handles high connection counts gracefully at the OS level, but it introduces its own class of problems: worker-thread exhaustion (<code class="BG">THREADPOOL</code> waits), excessive parallelism governed by MAXDOP and cost threshold settings, and scheduler contention visible as <code class="BG">CXPACKET</code> and <code class="BG">CXCONSUMER</code> waits. Connection pooling still matters enormously — ADO.NET and SqlClient pool connections client-side, and <code class="BG">sp_reset_connection</code> resets session state when a connection is reused — because establishing a fresh connection, authenticating, and allocating session memory is expensive no matter how efficient the thread pool is.""".replace('class="BG"', 'class="%s"' % C)),

# --- B34 heap-by-default -> clustered key depth ---
("""The <strong class="text-white">heap-by-default</strong> design in PostgreSQL means that row order on disk has no semantic significance unless you explicitly run CLUSTER. This gives PostgreSQL flexibility in insert patterns but means range scans on non-indexed columns always require a sequential scan of the entire heap. SQL Server's <strong class="text-white">clustered index as the table</strong> design means row locality for the clustering key is maintained automatically, making range queries on the clustering key very efficient — but it also means choosing a poor clustering key (like a random UUID or a frequently updated column) directly degrades physical storage layout and causes fragmentation.""",
 """The <strong class="text-white">clustered index as the table</strong> design means row locality for the clustering key is maintained automatically, making range queries on the clustering key very efficient — but it also means choosing a poor clustering key (a random GUID, a frequently updated wide column) directly degrades physical storage layout, fragments the table, and bloats every nonclustered index that carries the key as its row locator. Treat clustering-key selection as a physical design decision with permanent consequences, not a logical afterthought."""),

# --- B35 MVCC dead tuples -> version store monitoring ---
("""PostgreSQL's <strong class="text-white">MVCC implementation stores dead tuples in the heap</strong> and relies on VACUUM to clean them up. SQL Server's <strong class="text-white">row versioning stores versions in tempdb</strong> when RCSI or Snapshot Isolation is enabled, keeping the primary data pages clean but introducing tempdb as a potential bottleneck. In a heavily write-intensive SQL Server workload with RCSI enabled, tempdb I/O and version store growth become important monitoring targets.""",
 """SQL Server's <strong class="text-white">row versioning stores versions in tempdb</strong> when RCSI or Snapshot Isolation is enabled, keeping the primary data pages clean but making tempdb a potential bottleneck. In a heavily write-intensive workload with RCSI enabled, tempdb I/O latency and version-store growth become primary monitoring targets — and a single long-running transaction can pin versions in the store for hours, so tracking oldest-active-transaction age is as important as tracking the store's size."""),

# --- B36 WAL vs log -> transaction log roles ---
("""The <strong class="text-white">WAL in PostgreSQL</strong> is the basis not just for crash recovery but also for logical and streaming replication, point-in-time recovery, and Change Data Capture via logical decoding. Understanding WAL position, WAL lag, and WAL generation rate is essential for any PostgreSQL environment running replication. SQL Server's transaction log plays the same role, but SQL Server separates the mechanisms: log shipping, Always On Availability Groups, and transactional replication each interact with the log in distinct ways, and each has its own operational considerations.""",
 """The <strong class="text-white">transaction log</strong> is the basis not just for crash recovery but for the entire high-availability story: log shipping replays log backups, Always On Availability Groups stream log records to secondaries, transactional replication reads the log for published changes, and point-in-time recovery replays it to an arbitrary moment. Understanding log generation rate, VLF health, and what is preventing log truncation (<code class="BG">sys.databases.log_reuse_wait_desc</code> is the single most useful column for "why won't my log shrink") is essential operational knowledge.""".replace('class="BG"', 'class="%s"' % C)),

# --- B37 closing ---
("""None of these trade-offs make one system categorically better than the other — they make each system better suited for specific patterns, and they shape the specific skills and habits that make a DBA effective on each platform.""",
 """None of these are incidental details — they are the load-bearing walls of the engine, and they shape the specific skills and habits that make a DBA effective: watching version-store growth, sizing tempdb, choosing clustering keys deliberately, and keeping the transaction log backed up."""),

# --- takeaways ---
("""**PostgreSQL uses a process-per-connection model** with a shared buffer pool and heavy reliance on the OS page cache, while SQL Server uses a thread-pool model with a self-managed Buffer Pool — this difference drives many scaling and configuration decisions, including the near-mandatory use of connection poolers in PostgreSQL.""",
 """**SQL Server's thread-pool model (SQLOS)** with a self-managed Buffer Pool handles high connection counts efficiently, but shifts the operational focus to worker-thread health, MAXDOP and parallelism waits, and client-side connection pooling that reuses sessions via `sp_reset_connection`."""),

("""**MVCC is PostgreSQL's native concurrency mechanism**, giving readers and writers full independence without locking, but it requires ongoing VACUUM to clean dead tuple versions; SQL Server uses pessimistic locking by default, with RCSI offering MVCC-like behavior by routing row versions through tempdb.""",
 """**Locking is SQL Server's native concurrency mechanism**, with a lock hierarchy (database → table → page → row) and escalation past ~5,000 locks; RCSI and Snapshot Isolation offer MVCC-style non-blocking reads by routing row versions through tempdb's version store — at the cost of tempdb capacity you must monitor."""),

("""**Data storage at rest differs fundamentally**: PostgreSQL tables are heap files by default with no inherent row ordering, while SQL Server tables are typically stored as clustered indexes where physical row order follows the clustering key — making clustering key selection a critical design decision in SQL Server.""",
 """**Data storage at rest centers on the clustered index**: most SQL Server tables are B-trees where physical row order follows the clustering key — making clustering-key selection (narrow, static, ever-increasing) a critical physical design decision, with filegroups controlling which storage each object lives on."""),

("""**Background processes are architectural necessities, not overhead**: PostgreSQL's autovacuum, checkpointer, and WAL writer are as important to engine health as any query, and SQL Server's Lazy Writer, Checkpoint, and Log Writer threads serve the same structural roles.""",
 """**Background threads are architectural necessities, not overhead**: the Lazy Writer, Checkpoint, Log Writer, and ghost cleanup threads are as important to engine health as any query — and their waits (`WRITELOG`, free-buffer stalls) are early warning signals worth alerting on."""),

("""**The query pipeline — parse, rewrite/analyze, optimize, execute — is the same conceptual flow in both engines**, but SQL Server's aggressive plan caching and PostgreSQL's reliance on per-execution planning (for ad-hoc queries) create different optimization strategies and different failure modes, particularly around plan regression.""",
 """**The query pipeline — parse, algebrize, optimize, execute — rewards plan stability**: SQL Server's aggressive plan caching avoids recompilation overhead but introduces parameter sniffing as a failure mode, which is exactly what Query Store's flight-recorder history exists to diagnose."""),
]

def main():
    text = open(PATH).read()
    for i, (old, new) in enumerate(REPLACEMENTS):
        count = text.count(old)
        if count != 1:
            print(f'FAIL replacement {i}: found {count} occurrences')
            print('OLD SNIPPET:', old[:120])
            sys.exit(1)
        text = text.replace(old, new, 1)
    open(PATH, 'w').write(text)
    print(f'ch03: all {len(REPLACEMENTS)} replacements applied')

main()
