#!/usr/bin/env python3
"""Apply ch02 prose rewrites. Fails loudly on any non-unique match."""
import sys

PATH = '/home/hatch/workspace/dba-library/book/ch02-core-concepts.html'

REPLACEMENTS = [
# --- intro paragraph ---
("""Both PostgreSQL and SQL Server are built on decades of relational theory, and while their syntax and internal mechanics differ in meaningful ways, they share the same foundational DNA. This chapter walks through the core concepts that every DBA and developer must internalize — from how relational data is organized, to how transactions protect your data, to how the two databases differ in architecture and behavior. Understanding these building blocks will make everything else in this book click into place.""",
 """SQL Server is built on decades of relational theory, and this chapter walks through the core concepts that every DBA and developer must internalize — from how relational data is organized, to how transactions protect your data, to how the engine's architecture shapes everyday behavior. Understanding these building blocks will make everything else in this book click into place."""),

# --- data types intro ---
("""PostgreSQL and SQL Server share many of the same conceptual data types but differ significantly in naming, behavior, and available options.""",
 """SQL Server's data types each carry specific storage, behavior, and performance characteristics — and choosing well at design time prevents expensive migrations later."""),

# --- text types ---
("""One of the most consequential data type choices you will make is how to store <strong class="text-white">text</strong>. PostgreSQL's <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">TEXT</code> type is variable-length with no practical size limit and carries no performance penalty compared to <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">VARCHAR(n)</code>. In SQL Server, <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">VARCHAR(n)</code> and <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR(n)</code> are the standard choices. <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR</code> stores Unicode data using two bytes per character and should be used whenever you store multilingual content. A common production mistake is using <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR(MAX)</code> for every text column — this disables certain indexing optimizations and inflates storage unnecessarily.""",
 """One of the most consequential data type choices you will make is how to store <strong class="text-white">text</strong>. In SQL Server, <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">VARCHAR(n)</code> and <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR(n)</code> are the standard choices. <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR</code> stores Unicode data using two bytes per character and should be used whenever you store multilingual content — or data that may one day become multilingual. A common production mistake is using <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR(MAX)</code> for every text column — this disables certain indexing optimizations, inflates storage, and pushes large values off-row into LOB allocation units. Size your text columns deliberately: <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">VARCHAR(100)</code> for a name, <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR(4000)</code> for a description, and <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">(MAX)</code> only when the data genuinely has no bound."""),

# --- dates and timestamps ---
("""<strong class="text-white">Dates and timestamps</strong> are another area where the two databases diverge. PostgreSQL's <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">TIMESTAMPTZ</code> stores timestamps with full time zone awareness — it always converts to UTC internally and presents the value converted to the session's time zone. SQL Server's <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">DATETIMEOFFSET</code> carries the UTC offset with the value itself. For any application that runs across multiple time zones, or that stores audit records, using a timezone-aware type is not optional.""",
 """<strong class="text-white">Dates and timestamps</strong> deserve deliberate choice. SQL Server's <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">DATETIMEOFFSET</code> carries the UTC offset with the value itself, making it the right type for any application that runs across multiple time zones or stores audit records — a timestamp without its offset is ambiguous the moment it leaves the server that wrote it. For date-and-time values where the zone is fixed by convention, <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">DATETIME2</code> offers better precision and range than the legacy <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">DATETIME</code> type and should be your default. Avoid <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">DATETIME</code> in new schemas: its 3.33-millisecond rounding and narrower range are historical baggage."""),

# --- JSON ---
("""<strong class="text-white">JSON storage</strong> has become a first-class concern in both databases. PostgreSQL offers <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">JSON</code> and <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">JSONB</code> — <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">JSONB</code> stores the data in a decomposed binary format that supports indexing and is almost always the right choice. SQL Server has no native JSON column type, but it provides JSON functions that operate on <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR</code> columns storing JSON text. This is a meaningful architectural difference when your workload mixes structured and semi-structured data.""",
 """<strong class="text-white">JSON storage</strong> is a first-class concern in modern SQL Server. There is no native JSON column type; instead, JSON documents live in <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">NVARCHAR</code> columns and the engine provides a rich function library — <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">OPENJSON</code> to shred documents into rows, <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">JSON_VALUE</code> and <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">JSON_QUERY</code> to extract scalars and fragments, <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">FOR JSON</code> to serialize query results — plus the ability to index frequently-queried JSON properties through computed columns. This keeps semi-structured data inside the relational engine with full transactional guarantees, but it rewards discipline: validate JSON with <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ISJSON()</code> check constraints, index the properties you filter on, and never let a JSON column become an excuse to skip schema design."""),

# --- COALESCE ---
("""Both PostgreSQL and SQL Server offer a <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">COALESCE</code> function that returns the first non-NULL value in a list. This is the standard, portable way to substitute a default for a NULL. SQL Server also has <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ISNULL(value, replacement)</code>, which is a two-argument shortcut, but <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">COALESCE</code> is preferred because it is part of the SQL standard and works identically in both databases.""",
 """SQL Server's <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">COALESCE</code> function returns the first non-NULL value in a list — the standard, portable way to substitute a default for a NULL. SQL Server also has <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ISNULL(value, replacement)</code>, a two-argument shortcut, but <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">COALESCE</code> is preferred: it is part of the SQL standard, accepts more than two arguments, and follows standard data-type precedence rules that <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ISNULL</code> does not."""),

# --- isolation ---
("""Most production systems run at <strong class="text-white">Read Committed</strong>, which prevents dirty reads but allows non-repeatable reads and phantom reads. PostgreSQL defaults to Read Committed and implements it using Multi-Version Concurrency Control (MVCC), meaning readers never block writers. SQL Server defaults to Read Committed as well, but implements it using locking by default — readers can block writers unless you enable Read Committed Snapshot Isolation (RCSI).""",
 """Most production systems run at <strong class="text-white">Read Committed</strong>, which prevents dirty reads but allows non-repeatable reads and phantom reads. SQL Server implements Read Committed using locking by default — readers can block writers, and writers can block readers. Enabling <strong class="text-white">Read Committed Snapshot Isolation (RCSI)</strong> switches the engine to row versioning for reads: readers see a consistent snapshot served from tempdb and never block writers. RCSI is one of the highest-impact configuration decisions you will make, and most OLTP systems run better with it on — at the cost of tempdb capacity you must plan for."""),

# --- durability / WAL ---
("""<strong class="text-white">Durability</strong> means once a transaction is committed, it survives even a power failure. Both databases accomplish this through a write-ahead log (WAL in PostgreSQL, the transaction log in SQL Server). Every change is written to the log before it is applied to the data files, so the log can be replayed after a crash.""",
 """<strong class="text-white">Durability</strong> means once a transaction is committed, it survives even a power failure. SQL Server accomplishes this through the <strong class="text-white">transaction log</strong>: every change is written to the log before it is applied to the data files (write-ahead logging), so the log can be replayed after a crash. The transaction log is the single most important file in your SQL Server deployment — it is what makes point-in-time recovery possible, what availability groups ship to secondaries, and what fills up and halts all writes when nobody is backing it up."""),

# --- error within transaction ---
("""A pattern that trips up PostgreSQL developers coming from other databases: in PostgreSQL, if any statement inside a transaction raises an error, the entire transaction enters an <strong class="text-white">aborted state</strong> and every subsequent statement — including <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">COMMIT</code> — will fail until you issue a <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ROLLBACK</code>. SQL Server does not behave this way by default; a statement error does not automatically abort the entire transaction. This is why <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">SET XACT_ABORT ON</code> is a recommended practice in SQL Server stored procedures — it makes error behavior closer to what most developers expect.""",
 """Error handling inside transactions deserves your full attention. By default, SQL Server does <strong class="text-white">not</strong> abort an entire transaction when a single statement raises an error — the transaction stays open, locks stay held, and a subsequent <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">COMMIT</code> will happily commit partial work. This is why <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">SET XACT_ABORT ON</code> is a recommended practice in stored procedures: it makes any statement error terminate the batch and roll back the transaction, which is the behavior most developers expect. Pair it with <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">TRY...CATCH</code> blocks and check <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">XACT_STATE()</code> in the catch handler to decide whether the transaction is committable, doomed, or already gone — that distinction determines whether your catch block should commit, roll back, or simply log and re-throw."""),

# --- hierarchy intro ---
("""Both PostgreSQL and SQL Server organize objects into a hierarchy, but the hierarchy means different things in each system, and conflating them causes genuine confusion.""",
 """SQL Server organizes objects into a hierarchy — server, database, schema, object — and misunderstanding any level of it causes genuine confusion in production."""),

# --- PG hierarchy paragraph -> SQL Server cross-db deepening ---
("""In <strong class="text-white">PostgreSQL</strong>, the hierarchy is: Cluster → Database → Schema → Object. A PostgreSQL cluster is the running instance, and it hosts multiple databases. Like SQL Server, databases within a cluster are isolated — you cannot join tables across databases within a single query without extensions like <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">dblink</code> or <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">postgres_fdw</code>. Within a database, schemas serve the same organizational purpose. The default schema is <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">public</code>. PostgreSQL also has a <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">search_path</code> variable that determines which schemas are searched when an unqualified object name is used — misconfigured search paths are a source of subtle bugs in multi-schema applications.""",
 """Cross-database access in SQL Server deserves a closer look, because it is both powerful and easy to misuse. Three-part naming (<code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">database.schema.table</code>) lets a query span databases on the same instance, but cross-database ownership chaining is off by default — a user needs permissions in <em>both</em> databases, which surprises teams that assume access flows downhill. When databases move between servers — Availability Group failovers, log-shipped restores, migrations — the login-to-user mapping breaks and you get orphaned users. Partially contained databases, which authenticate at the database level with no server login at all, eliminate this entire class of problem. Choose containment deliberately for any database with a mobile lifestyle."""),

# --- default privileges paragraph ---
("""Understanding the object hierarchy matters particularly for permission management. In SQL Server, granting <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">SELECT</code> on a schema grants access to all current and future objects within it — a powerful pattern for role-based access control. In PostgreSQL, default privileges need to be set explicitly with <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ALTER DEFAULT PRIVILEGES</code> to extend access to future objects. Many PostgreSQL environments have been burned by creating a new table only to discover that application users cannot access it because the default privilege grant was not set up correctly.""",
 """Understanding the object hierarchy matters particularly for permission management. In SQL Server, granting <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">SELECT</code> on a schema grants access to all current and future objects within it — a powerful pattern for role-based access control that avoids the per-table grant treadmill. Design your schemas as security boundaries from the start: an <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">app</code> schema for application tables, a <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">reporting</code> schema for views, a <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">staging</code> schema for ETL — then grant at the schema level and let new objects inherit the right permissions automatically."""),

# --- users and roles ---
("""Users and roles are another area of divergence. PostgreSQL has a unified concept: everything is a role. A role with the LOGIN attribute is what most people call a user. A role without LOGIN is a group role. SQL Server separates logins (server-level identities) from users (database-level identities) — a login maps to a user within each database, and a user who exists in one database has no automatic presence in another.""",
 """SQL Server separates <strong class="text-white">logins</strong> (server-level identities) from <strong class="text-white">users</strong> (database-level identities) — a login maps to a user within each database, and a user who exists in one database has no automatic presence in another. Internalize this split early: revoking a login's CONNECT permission is not the same as dropping its database users, and orphaned users — database users whose login no longer exists, common after restores to a different server — are a classic production gotcha that <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">ALTER USER ... WITH LOGIN</code> exists to fix. Contained databases, which authenticate users without any server-level login at all, are the modern answer for databases that move between servers."""),

# --- takeaway: data types ---
("""Data type selection is a design decision with lasting consequences: use `NUMERIC`/`DECIMAL` for financial data, timezone-aware types for any timestamp that crosses time zones, and understand the difference between PostgreSQL's native `JSONB` and SQL Server's JSON-over-`NVARCHAR` approach before choosing an architecture.""",
 """Data type selection is a design decision with lasting consequences: use `NUMERIC`/`DECIMAL` for financial data, `DATETIMEOFFSET` for any timestamp that crosses time zones, size `VARCHAR`/`NVARCHAR` deliberately instead of defaulting to `(MAX)`, and use the JSON function library with indexed computed columns when semi-structured data must live in the relational engine."""),

# --- takeaway: ACID ---
("""ACID transactions are enforced differently in the two databases: PostgreSQL uses MVCC so readers never block writers, while SQL Server uses locking by default and requires Read Committed Snapshot Isolation to achieve non-blocking reads; additionally, PostgreSQL's error-within-transaction behavior aborts the entire transaction, unlike SQL Server's default.""",
 """ACID transactions in SQL Server rest on the transaction log for durability and on your isolation choice for concurrency: locking-based Read Committed by default, or row-versioned Read Committed Snapshot Isolation when readers must not block writers; pair every explicit transaction with `SET XACT_ABORT ON` and `TRY...CATCH` so a statement error can never leave partial work committed."""),

# --- takeaway: hierarchy ---
("""The object hierarchy — server, database, schema, table — functions similarly in both databases conceptually, but the details of cross-database access, search paths, default privileges, and the login-versus-user distinction are meaningful differences that every DBA working across both platforms must internalize.""",
 """The object hierarchy — server, database, schema, table — is a security and organization tool, not just naming: design schemas as permission boundaries, grant at the schema level so future objects inherit correctly, and master the login-versus-user split (including orphaned users after restores) before it bites you in production."""),
]

def main():
    text = open(PATH).read()
    for i, (old, new) in enumerate(REPLACEMENTS):
        count = text.count(old)
        if count != 1:
            print(f'FAIL replacement {i}: found {count} occurrences')
            sys.exit(1)
        text = text.replace(old, new, 1)
    open(PATH, 'w').write(text)
    print(f'ch02: all {len(REPLACEMENTS)} replacements applied')

main()
