#!/usr/bin/env python3
"""Rewrite remaining PostgreSQL content in b5-ch04 (v3)."""
import sys

PATH = "/home/hatch/workspace/dba-library/book5/b5-ch04-cloud-dba-role.html"

with open(PATH, encoding="utf-8") as f:
    t = f.read()

CODE = 'class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs"'
reps = []

# intro
reps.append((
"""If you have spent years tuning PostgreSQL shared_buffers, managing SQL Server Always On Availability Groups, and writing runbooks for failover procedures at 2 AM""",
"""If you have spent years tuning SQL Server max server memory, managing Always On Availability Groups, and writing runbooks for failover procedures at 2 AM"""
))
# implicit contract
reps.append((
"""When you move from self-managed PostgreSQL to Amazon RDS, you are entering into an implicit contract.""",
"""When you move from self-managed SQL Server to Amazon RDS, you are entering into an implicit contract."""
))
# 4.2 heading
reps.append((
"""4.2 Access Patterns and Permissions: From pg_hba.conf to IAM""",
"""4.2 Access Patterns and Permissions: From Server Logins to IAM"""
))
# IAM paragraph
reps.append((
"""With IAM database authentication enabled on RDS PostgreSQL, a user connects using a short-lived authentication token generated by the AWS IAM service rather than a static password. The token is valid for 15 minutes and is generated using the AWS credentials of the calling identity — an EC2 instance profile, a Lambda execution role, or a developer's IAM user. The database-side configuration still uses pg_hba.conf, but the method becomes <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">md5</code> or <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">scram-sha-256</code> is bypassed in favor of the IAM token validation path.""",
f"""With IAM database authentication enabled on RDS for SQL Server, a login connects using a short-lived authentication token generated by the AWS IAM service rather than a static password. The token is valid for 15 minutes and is generated using the AWS credentials of the calling identity — an EC2 instance profile, a Lambda execution role, or a developer's IAM user. The database-side configuration still uses SQL Server logins and database users, but the credential presented at connect time is the IAM token instead of the login's password."""
))
# pg_reload_conf paragraph
reps.append((
"""Rotating credentials means updating IAM policies, not editing pg_hba.conf and running <code class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs">pg_reload_conf()</code>.""",
"""Rotating credentials means updating IAM policies, not editing server logins and coordinating password rotations across application servers."""
))
# Patroni paragraph
reps.append((
"""A PostgreSQL streaming replication setup with Patroni, HAProxy, and etcd requires significant operational investment. SQL Server AlwaysOn Availability Groups require Windows Server Failover Clustering, shared storage or synchronous replication, and careful listener configuration.""",
"""A SQL Server Always On availability group with a Windows Server Failover Cluster, listener, and quorum configuration requires significant operational investment. Self-managed failover clustering requires quorum votes, witness configuration, and careful patch sequencing across nodes."""
))
# Aurora CLI block -> Aurora MySQL
reps.append((
"""# Create an Aurora PostgreSQL cluster with two replicas in different AZs\\naws rds create-db-cluster \\\\\\n  --db-cluster-identifier prod-aurora-cluster \\\\\\n  --engine aurora-postgresql \\\\\\n  --engine-version 15.4 \\\\\\n""",
"""# Create an Aurora MySQL cluster with two replicas in different AZs\\naws rds create-db-cluster \\\\\\n  --db-cluster-identifier prod-aurora-cluster \\\\\\n  --engine aurora-mysql \\\\\\n  --engine-version 8.0.mysql_aurora.3.08.0 \\\\\\n"""
))
reps.append((
"""  --db-instance-identifier prod-aurora-writer \\\\\\n  --db-instance-class db.r6g.2xlarge \\\\\\n  --engine aurora-postgresql\\n""",
"""  --db-instance-identifier prod-aurora-writer \\\\\\n  --db-instance-class db.r7g.2xlarge \\\\\\n  --engine aurora-mysql\\n"""
))
reps.append((
"""  --db-instance-identifier prod-aurora-reader-1 \\\\\\n  --db-instance-class db.r6g.xlarge \\\\\\n  --engine aurora-postgresql \\\\\\n""",
"""  --db-instance-identifier prod-aurora-reader-1 \\\\\\n  --db-instance-class db.r7g.xlarge \\\\\\n  --engine aurora-mysql \\\\\\n"""
))
# PI paragraph
reps.append((
"""Performance Insights is the cloud analog to Oracle's Active Session History and a significant improvement over what most PostgreSQL on-premises deployments have out of the box.""",
"""Performance Insights is the cloud analog to Oracle's Active Session History and a significant improvement over what most self-managed SQL Server deployments have out of the box."""
))
# monitoring tradeoff
reps.append((
"""they do not expose lock wait graphs as clearly as pg_locks queries do on self-managed PostgreSQL, and correlating application traces""",
"""they do not expose lock wait graphs as clearly as sys.dm_tran_locks queries do on self-managed SQL Server, and correlating application traces"""
))
# provisioning paragraph
reps.append((
"""In on-premises environments, provisioning a PostgreSQL server involved coordinating with a server team, a storage team, and a network team, filling out a change request, and waiting.""",
"""In on-premises environments, provisioning a SQL Server VM involved coordinating with a server team, a storage team, and a network team, filling out a change request, and waiting."""
))
# Terraform block
reps.append((
"""# Terraform: production Aurora PostgreSQL cluster\\nresource "aws_rds_cluster" "prod" {\\n  cluster_identifier      = "prod-aurora-pg"\\n  engine                  = "aurora-postgresql"\\n  engine_version          = "15.4\"""",
"""# Terraform: production Aurora MySQL cluster\\nresource "aws_rds_cluster" "prod" {\\n  cluster_identifier      = "prod-aurora-mysql"\\n  engine                  = "aurora-mysql"\\n  engine_version          = "8.0.mysql_aurora.3.08.0\""""
))
reps.append((
"""enabled_cloudwatch_logs_exports = ["postgresql"]""",
"""enabled_cloudwatch_logs_exports = ["error", "general", "slowquery"]"""
))
reps.append((
'''  identifier         = "prod-aurora-pg-writer''',
'''  identifier         = "prod-aurora-mysql-writer'''
))
reps.append((
'''  identifier         = "prod-aurora-pg-reader-${count.index + 1}\\''',
'''  identifier         = "prod-aurora-mysql-reader-${count.index + 1}\\'''
))
reps.append((
'''  instance_class     = "db.r6g.2xlarge\\''',
'''  instance_class     = "db.r7g.2xlarge\\'''
))
reps.append((
'''  instance_class     = "db.r6g.xlarge\\''',
'''  instance_class     = "db.r7g.xlarge\\'''
))
reps.append((
"""  name   = "prod-aurora-pg15"\\n  family = "aurora-postgresql15"\\n\\n  parameter {\\n    name         = "shared_preload_libraries"\\n    value        = "pg_stat_statements,auto_explain"\\n    apply_method = "pending-reboot"\\n  }\\n\\n  parameter {\\n    name         = "log_min_duration_statement"\\n    value        = "1000"\\n    apply_method = "immediate"\\n  }\\n\\n  parameter {\\n    name         = "autovacuum_vacuum_scale_factor"\\n    value        = "0.01"\\n    apply_method = "immediate"\\n  }\\n\\n  parameter {\\n    name         = "autovacuum_analyze_scale_factor"\\n    value        = "0.005"\\n    apply_method = "immediate"\\n""",
"""  name   = "prod-aurora-mysql80"\\n  family = "aurora-mysql8.0"\\n\\n  parameter {\\n    name         = "slow_query_log"\\n    value        = "1"\\n    apply_method = "immediate"\\n  }\\n\\n  parameter {\\n    name         = "long_query_time"\\n    value        = "1"\\n    apply_method = "immediate"\\n"""
))

failed = []
for old, new in reps:
    n = t.count(old)
    if n == 1:
        t = t.replace(old, new)
    else:
        failed.append((n, old[:90]))

if failed:
    print("FAILED REPLACEMENTS:")
    for n, s in failed:
        print(f"  count={n}: {s}")
    sys.exit(1)

with open(PATH, "w", encoding="utf-8") as f:
    f.write(t)
print("ch04 v3 OK:", len(reps), "replacements applied")
