#!/usr/bin/env python3
"""Rewrite remaining PostgreSQL content in b5-ch04 (v4, explicit newlines)."""
import sys

PATH = "/home/hatch/workspace/dba-library/book5/b5-ch04-cloud-dba-role.html"

with open(PATH, encoding="utf-8") as f:
    t = f.read()

NL = "\n"
BS = "\\"
CODE = 'class="bg-gray-800 px-1.5 py-0.5 rounded text-blue-300 text-xs"'
reps = []

reps.append((
"If you have spent years tuning PostgreSQL shared_buffers, managing SQL Server Always On Availability Groups, and writing runbooks for failover procedures at 2 AM",
"If you have spent years tuning SQL Server max server memory, managing Always On Availability Groups, and writing runbooks for failover procedures at 2 AM"
))
reps.append((
"When you move from self-managed PostgreSQL to Amazon RDS, you are entering into an implicit contract.",
"When you move from self-managed SQL Server to Amazon RDS, you are entering into an implicit contract."
))
reps.append((
"4.2 Access Patterns and Permissions: From pg_hba.conf to IAM",
"4.2 Access Patterns and Permissions: From Server Logins to IAM"
))
IAM_PARA_OLD = (
"With IAM database authentication enabled on RDS PostgreSQL, a user connects using a short-lived authentication token generated by the AWS IAM service rather than a static password. The token is valid for 15 minutes and is generated using the AWS credentials of the calling identity — an EC2 instance profile, a Lambda execution role, or a developer's IAM user. The database-side configuration still uses pg_hba.conf, but the method becomes <code " + CODE + ">md5</code> or <code " + CODE + ">scram-sha-256</code> is bypassed in favor of the IAM token validation path."
)
IAM_PARA_NEW = (
"With IAM database authentication enabled on RDS for SQL Server, a login connects using a short-lived authentication token generated by the AWS IAM service rather than a static password. The token is valid for 15 minutes and is generated using the AWS credentials of the calling identity — an EC2 instance profile, a Lambda execution role, or a developer's IAM user. The database-side configuration still uses SQL Server logins and database users, but the credential presented at connect time is the IAM token instead of the login's password."
)
reps.append((IAM_PARA_OLD, IAM_PARA_NEW))
reps.append((
"Rotating credentials means updating IAM policies, not editing pg_hba.conf and running <code " + CODE + ">pg_reload_conf()</code>.",
"Rotating credentials means updating IAM policies, not editing server logins and coordinating password rotations across application servers."
))
reps.append((
"A PostgreSQL streaming replication setup with Patroni, HAProxy, and etcd requires significant operational investment. SQL Server AlwaysOn Availability Groups require Windows Server Failover Clustering, shared storage or synchronous replication, and careful listener configuration.",
"A self-managed SQL Server Always On availability group with a Windows Server Failover Cluster, listener, and quorum configuration requires significant operational investment. Self-managed failover clustering demands quorum votes, witness configuration, and careful patch sequencing across nodes."
))
# Aurora CLI block -> Aurora MySQL
reps.append((
"# Create an Aurora PostgreSQL cluster with two replicas in different AZs" + NL +
"aws rds create-db-cluster " + BS + NL +
"  --db-cluster-identifier prod-aurora-cluster " + BS + NL +
"  --engine aurora-postgresql " + BS + NL +
"  --engine-version 15.4 " + BS + NL,
"# Create an Aurora MySQL cluster with two replicas in different AZs" + NL +
"aws rds create-db-cluster " + BS + NL +
"  --db-cluster-identifier prod-aurora-cluster " + BS + NL +
"  --engine aurora-mysql " + BS + NL +
"  --engine-version 8.0.mysql_aurora.3.08.0 " + BS + NL
))
reps.append((
"  --db-instance-identifier prod-aurora-writer " + BS + NL +
"  --db-instance-class db.r6g.2xlarge " + BS + NL +
"  --engine aurora-postgresql" + NL,
"  --db-instance-identifier prod-aurora-writer " + BS + NL +
"  --db-instance-class db.r7g.2xlarge " + BS + NL +
"  --engine aurora-mysql" + NL
))
reps.append((
"  --db-instance-identifier prod-aurora-reader-1 " + BS + NL +
"  --db-instance-class db.r6g.xlarge " + BS + NL +
"  --engine aurora-postgresql " + BS + NL,
"  --db-instance-identifier prod-aurora-reader-1 " + BS + NL +
"  --db-instance-class db.r7g.xlarge " + BS + NL +
"  --engine aurora-mysql " + BS + NL
))
reps.append((
"Performance Insights is the cloud analog to Oracle's Active Session History and a significant improvement over what most PostgreSQL on-premises deployments have out of the box.",
"Performance Insights is the cloud analog to Oracle's Active Session History and a significant improvement over what most self-managed SQL Server deployments have out of the box."
))
reps.append((
"they do not expose lock wait graphs as clearly as pg_locks queries do on self-managed PostgreSQL, and correlating application traces",
"they do not expose lock wait graphs as clearly as sys.dm_tran_locks queries do on self-managed SQL Server, and correlating application traces"
))
reps.append((
"In on-premises environments, provisioning a PostgreSQL server involved coordinating with a server team, a storage team, and a network team, filling out a change request, and waiting.",
"In on-premises environments, provisioning a SQL Server VM involved coordinating with a server team, a storage team, and a network team, filling out a change request, and waiting."
))
# Terraform block
reps.append((
"# Terraform: production Aurora PostgreSQL cluster" + NL + 'resource "aws_rds_cluster" "prod" {' + NL +
'  cluster_identifier      = "prod-aurora-pg"' + NL +
'  engine                  = "aurora-postgresql"' + NL +
'  engine_version          = "15.4"',
"# Terraform: production Aurora MySQL cluster" + NL + 'resource "aws_rds_cluster" "prod" {' + NL +
'  cluster_identifier      = "prod-aurora-mysql"' + NL +
'  engine                  = "aurora-mysql"' + NL +
'  engine_version          = "8.0.mysql_aurora.3.08.0"'
))
reps.append((
'enabled_cloudwatch_logs_exports = ["postgresql"]',
'enabled_cloudwatch_logs_exports = ["error", "general", "slowquery"]'
))
reps.append((
'identifier         = "prod-aurora-pg-writer"',
'identifier         = "prod-aurora-mysql-writer"'
))
reps.append((
'identifier         = "prod-aurora-pg-reader-${count.index + 1}"',
'identifier         = "prod-aurora-mysql-reader-${count.index + 1}"'
))
reps.append((
'instance_class     = "db.r6g.2xlarge"',
'instance_class     = "db.r7g.2xlarge"'
))
reps.append((
'instance_class     = "db.r6g.xlarge"',
'instance_class     = "db.r7g.xlarge"'
))
reps.append((
'  name   = "prod-aurora-pg15"' + NL + '  family = "aurora-postgresql15"',
'  name   = "prod-aurora-mysql80"' + NL + '  family = "aurora-mysql8.0"'
))
reps.append((
'    name         = "shared_preload_libraries"' + NL +
'    value        = "pg_stat_statements,auto_explain"' + NL +
'    apply_method = "pending-reboot"',
'    name         = "slow_query_log"' + NL +
'    value        = "1"' + NL +
'    apply_method = "immediate"'
))
reps.append((
'    name         = "log_min_duration_statement"' + NL +
'    value        = "1000"' + NL +
'    apply_method = "immediate"',
'    name         = "long_query_time"' + NL +
'    value        = "1"' + NL +
'    apply_method = "immediate"'
))
reps.append((
'    name         = "autovacuum_vacuum_scale_factor"' + NL +
'    value        = "0.01"' + NL +
'    apply_method = "immediate"',
'    # (removed PostgreSQL autovacuum tuning — not applicable to Aurora MySQL)'
))

failed = []
for old, new in reps:
    n = t.count(old)
    if n == 1:
        t = t.replace(old, new)
    else:
        failed.append((n, old[:90]))

# clean up the placeholder comment marker if the extra closing-brace lines remain
if failed:
    print("FAILED REPLACEMENTS:")
    for n, s in failed:
        print("  count=" + str(n) + ": " + s)
    sys.exit(1)

with open(PATH, "w", encoding="utf-8") as f:
    f.write(t)
print("ch04 v4 OK:", len(reps), "replacements applied")
